### ISSUE TITLE
Build failed without -std=c99 or -std=gnu99

### ISSUE THREAD

**Issue by remicollet** [sektioneins/suhosin7#3]
ON RHEL-7 (gcc 4.8)

```
/builddir/build/BUILD/php70-php-suhosin-0.10.0/NTS/execute.c:159:2: error: 'for' loop initial declarations are only allowed in C99 mode
  for (int i = 0; i < slen-3; i++) {
  ^
/builddir/build/BUILD/php70-php-suhosin-0.10.0/NTS/execute.c:159:2: note: use option -std=c99 or -std=gnu99 to compile your code
```

**Comment by bef** [comment]
The code is written in C11 and compiles just fine with clang or with gcc and `-std=c11`.
Is there any technical reason to still use C99?

**Comment by remicollet** [comment]
>  Is there any technical reason to still use C99?

This is not the question.
The problem is that c99 or c11 are not enable by default with gcc < 5. So the build fails.

The option (c99 is enough) need to add to CFLAGS.

A simple CFLAGS="$CFLAGS -std=c99" in config.m4 should be enough.
