### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by szepeviktor** [sektioneins/suhosin7#5]
Please provide tests, I am willing to implement TravisCI integration.

**Comment by bef** [comment]
Tests will be provided with each feature implemented or ported from suhosin 0.9.
If you happen to come across implemented features without proper test cases, please leave a comment.

**Comment by szepeviktor** [comment]
```
=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   40
---------------------------------------------------------------------

Number of tests :   72                55
Tests skipped   :   17 ( 23.6%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   55 ( 76.4%) (100.0%)
---------------------------------------------------------------------
Time taken      :    2 seconds
=====================================================================
```

Would you welcome a Travis PR?

**Comment by bef** [comment]
Sure. Thank you for the offer. In the long run a proper CI integration would be nice, for suhosin as well as suhosin7. I just never had the time to set it up for all relevant architectures and options, e.g. x86 32bit+64bit / ARM / ARM64, PHP with ZTS and without ZTS, numerous supported PHP versions, different compilers (clang + GCC), with and without experimental features... .and so on. Also, suhosin behaves differently in combination with some PHP modules, such as opcache, apc or proprietary code encryption modules. These combinations would have to be tested as well. The entire task of integrating suhosin into a CI appears appealing at first, but may take a lot of effort.

**Comment by szepeviktor** [comment]
> numerous supported PHP versions

What did you mean?

**Comment by bef** [comment]
Suhosin supports several 5.x versions. Suhosin7 will most likely eventually support php 7.x (apart from 7.0) some time in the future.

**Comment by bef** [comment]
travis-ci is merged. thanks for the help.
